name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 4 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 360 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
        stale-pr-message: 'This PR is stale because it has been open 360 days with no activity.'
        close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
        days-before-issue-stale: 360
        days-before-pr-stale: 360
        days-before-issue-close: 5
        days-before-pr-close: -1
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        exempt-issue-labels: 'awaiting-feedback,awaiting-answers,work-in-progress'
        exempt-pr-labels: 'awaiting-approval,work-in-progress'
